# Generated by Django 4.0.5 on 2022-06-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_poi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.CharField(blank=True, choices=[('Inner Boston', 'Inner Boston'), ('Outer Boston', 'Outer Boston')], max_length=20, null=True),
        ),
    ]
