# Generated by Django 4.0.5 on 2022-06-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='borough',
            new_name='county',
        ),
    ]
